entries:
- terrain_id: 5
  section: 0
  tsx_path: assets/tilesets/ADWinter_TileB.tsx
  tile_id: 73
- terrain_id: 5
  section: 1
  tsx_path: assets/tilesets/ADWinter_TileB.tsx
  tile_id: 41
- terrain_id: 5
  section: 2
  tsx_path: assets/tilesets/ADWinter_TileB.tsx
  tile_id: 57
- terrain_id: 2
  section: 2
  tsx_path: assets/tilesets/TileB_exterior1.tsx
  tile_id: 65
- terrain_id: 4
  section: 0
  tsx_path: assets/tilesets/TileB_exterior2.tsx
  tile_id: 81
- terrain_id: 2
  section: 1
  tsx_path: assets/tilesets/TileB_exterior1.tsx
  tile_id: 49
- terrain_id: 2
  section: 0
  tsx_path: assets/tilesets/TileB_exterior1.tsx
  tile_id: 81
- terrain_id: 4
  section: 1
  tsx_path: assets/tilesets/TileB_exterior2.tsx
  tile_id: 65
- terrain_id: 4
  section: 2
  tsx_path: assets/tilesets/TileB_exterior2.tsx
  tile_id: 65
